CREATE TABLE [Artifact] (
  [ArtifactID] varchar(20),
  [Location] nvarchar(13),
  [Position] varchar(50),
  [MetersNorthSouth] smallint,
  [NorthOrSouth] varchar(1),
  [MetersEastWest] smallint,
  [EastOrWest] varchar(1),
  [BurialNumber] smallint,
  [ExcavationYear] <type>,
  [Title] varchar(100),
  [Description] varchar(MAX),
  [Material] varchar(20),
  [Condition] varchar(20),
  [Dimensions] varchar(20),
  [Notes] varchar(MAX),
  [ArtifactEra] varchar(30),
  [Provenance] varchar(30),
  [IsSurfaceFind] bit,
  [FindDay] tinyint,
  [FindMonth] intyint,
  [FindYear] smallint,
  [FindDate] <type>,
  [Finder] <type>,
  [ExcavatorNum] varchar(20),
  [KomAushimEntryDate] date,
  [StorageSite] varchar(50),
  [LocationAtSite] varchar(100)),
  [ConservationNotes] varchar(500),
  [HasPhotos] bit,
  [Colors?] <type>,
  PRIMARY KEY ([ArtifactID])
);